FROM node:16

LABEL authors="tirane"

RUN apt-get update && \
    apt-get install -y wget gnupg jq && \
    wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - && \
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list && \
    apt-get update && \
    apt-get install -y mongodb-org-tools

WORKDIR /server

COPY server/. .

RUN npm install && \
    chmod +x startup.sh

COPY dump/sample_training/posts.csv /dump/sample_training/posts.csv
COPY job/* .
EXPOSE 5050

CMD ["./startup.sh"]