# Use the official Node.js 16 image as the base image
FROM node:16
LABEL authors="tirane"


LABEL authors="tirane"

RUN apt-get update && \
    apt-get install -y wget gnupg && \
    wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - && \
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list && \
    apt-get update && \
    apt-get install -y mongodb-org-tools

WORKDIR /app
COPY package*.json ./

# Install dependencies, including Express.js
RUN npm install
COPY . .

RUN npm run build
RUN npx update-browserslist-db@latest
EXPOSE 3000
CMD ["npm", "start"]