apiVersion: batch/v1
kind: Job
metadata:
  name: patchdb-job
spec:
  template:
    spec:
      containers:
      - name:  "patchdb-job"
        image: "{{ .Values.JobImage.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "/server/k8s_job.sh"]
        envFrom:
          - secretRef:
              name: patchdb-env
        volumeMounts:
        - name: post-values
          mountPath: /config
        - name: dump
          mountPath: /dump
      volumes:
      - name: post-values
        configMap:
          name: {{ include "mongo-app.fullname" . }}-post-values
      - name: dump
        persistentVolumeClaim:
          claimName: {{ include "mongo-app.fullname" . }}-dump-pvc
      restartPolicy: Never
  backoffLimit: 4